version: "3.3"
# Указываем раздел со связанными сервисами
services:
  # Первый сервис, nginx
  # Первый сервис, nginx
  nginx:
    image: nginx:latest
    # Пробрасываем порты 80 для http и 443 для https
    ports:
      - "80:80"
      - "443:443"
    # Опциональный параметр с именем контейнера
    container_name: proxy_nginx
    volumes:
      # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./nginx:/etc/nginx/conf.d
      # Монтируем папку с логами на хост машину для более удобного доступа
      - ./logs:/var/log/nginx/
    depends_on:
      - nuxt
  # Второй сервис Nuxt.js приложение
  nodejs:
    container_name: nodejs
    build: .
    # Так же пробрасываем порт на котором висит приложение
    image: nodejs
    ports:
      - "3000:3000"
    volumes:
      - ./static:/web/static
    restart: always
